name: base
channels:
  - potassco
  - conda-forge
  - colomoto
  - colomoto/label/fake
  - pauleve
  - daemontus
  - creda
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - conda==24.3.0
  - setuptools
  - pip
  - wheel
  - conda-content-trust
  - conda-libmamba-solver
  - menuinst
  - libarchive
  - libmamba
  - libmambapy
  - openjdk
  - pyqt=5.9.9999
  - graphviz
  - imagemagick
  - ipywidgets
  - matplotlib
  - networkx
  - nomkl
  - notebook
  - pandas
  - pyarrow
  - pydot
  - python-graphviz
  - scikit-learn
  - seaborn
  - r-base[version='>=4.1']
  - rpy2
  - cmappy
  - cython
  - omnipath
  - qnorm
  - asprin==3.1.1=py_0
  - bnettoprime==1.0=h6bb024c_0
  - bns==1.3=0
  - booleannet==1.2.8=py_0
  - boolsim==1.2=0
  - caspo==4.0.1=py_1
  - clingo==5.7.1=py311h3fd9d12_0
  - eqntott==1.0=1
  - erode-python==0.7.2=py_0
  - espresso-logic-minimizer==9999=h14c3975_0
  - its==20210125=0
  - nusmv-a==1.2=h6bb024c_0
  - nusmv-arctl==2.2.2=0
  - nusmv==2.6.0=0
  - pint==2019.05.24=1
  - r-boolnet=2.1.9
  - biodivine_aeon==0.0.9a3=py311h9bf148f_0
  - cabean==1.0.0=0
  - ginsim==3.0.0b=12
  - libsbml-plus-packages==5.20.0=hbee6a8b_0
  - maboss==2.5.5=h2bc3f7f_1
  - pyboolnet==3.0.10.post1=py_0
  - algorecell_types==1.0=py_0
  - bns-python==0.2=py_0
  - bonesis==0.6.5=py_0
  - boolsim-python==0.5=py_0
  - cabean-python==1.0=py_0
  - caspo-control==1.0=py_0
  - casq==1.0.3=py_0
  - colomoto_jupyter==0.8.8=py_0
  - ginsim-python==0.4.3=py_0
  - mpbn==3.4=py_0
  - nordic==2.4.4=py_0
  - pyactonet==1.0=py_0
  - pymaboss==0.8.7=py_0
  - pypint==1.6.3=py_0
  - pystablemotifs==3.0.6=py_0
  - scboolseq==2.0.1=py_0
prefix: /opt/conda
