name: base
channels:
  - potassco
  - conda-forge
  - colomoto
  - colomoto/label/fake
  - pauleve
  - daemontus
  - creda
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - conda=25.9.1
  - setuptools
  - pip
  - wheel
  - conda-anaconda-telemetry[version='>=0.2.0']
  - conda-anaconda-tos[version='>=0.2.1']
  - conda-content-trust
  - conda-libmamba-solver
  - menuinst
  - anaconda-anon-usage
  - libmambapy
  - libmamba
  - libarchive
  - pyqt=5.9.9999
  - openjdk
  - notebook
  - numpy[version='>=2.2']
  - scikit-learn
  - ipywidgets
  - networkx
  - python-graphviz
  - seaborn
  - graphviz
  - matplotlib
  - pandas
  - pyarrow
  - imagemagick
  - pydot
  - nomkl
  - ipylab[version='>=1.1.0']
  - rpy2[version='<3.6.4']
  - r-base[version='>=4.1']
  - pyeda
  - omnipath
  - z3-solver
  - gurobi
  - python-libsbml
  - qnorm
  - cython
  - cmappy
  - asprin=3.1.1=py_0
  - its=20210125=0
  - clingo=5.8.0=py312h3fd9d12_0
  - erode-python=0.7.2=py_0
  - cabean=1.0.0=0
  - booleannet=1.2.8=py_0
  - ginsim=3.0.0b=13
  - nusmv-a=1.2=h6bb024c_0
  - nusmv=2.7.0=0
  - boolsim=1.2=0
  - caspo=4.0.1=py_1
  - r-boolnet=2.1.9
  - bns=1.3=h2bc3f7f_0
  - pint=2019.05.24=1
  - boolean.py=5.0=pyhd8ed1ab_0
  - pyboolnet=3.0.16=py312_0
  - optboolnet=1.0.1=py_0
  - maboss=2.6.5=h656b026_1
  - biodivine_aeon=1.2.3=py312h9bf148f_0
  - pyactonet=1.0=py_0
  - mpbn=4.2=py_0
  - scboolseq=2.3.2=py_0
  - cabean-python=1.0=py_0
  - pymaboss=0.8.12=py_0
  - caspo-control=1.0=py_0
  - algorecell_types=1.0=py_0
  - casq=1.3.3=pyhd8ed1ab_1
  - nordic=2.7.1=py_0
  - colomoto_jupyter=0.9.2=py_0
  - boolsim-python=0.5=py_0
  - pypint=1.6.4=py_0
  - pydruglogics=0.1.10=py_0
  - bns-python=0.2=py_0
  - boon=1.28=py_0
  - bonesis=0.6.8.1=py_0
  - pystablemotifs=3.0.6=py_0
  - ginsim-python=0.4.6=py_0
prefix: /opt/conda
